### ISSUE TITLE
Simple custom range doesn't compile

### ISSUE THREAD

**Issue by raygray** [Microsoft/Range-V3-VS2015#24]
A very simple custom range code as shown in [Range-V3 documentation](https://ericniebler.github.io/range-v3/index.html#tutorial-quick-start) (under **Create Custom Ranges**) fails to compile: [custom_range_errors.txt](https://github.com/Microsoft/Range-V3-VS2015/files/1424827/custom_range_errors.txt).

**Comment by ericniebler** [comment]
Range-v3-VS2015 is a ~2 year old fork of range-v3. Many interfaces have changed. I recommend using the docs that are part of Range-V3-VS2015 rather than looking at range-v3's docs.

**Comment by raygray** [comment]
Thank you for clarification (I've just followed the link mentioned in README.md). I hope the VS compiler would eventually catch the standard. And big thanks for your excellent - truly earthshaking - lib!
