### ISSUE TITLE
Which version of range-v3 is compatible?

### ISSUE THREAD

**Issue by xylosper** [Microsoft/Range-V3-VS2015#28]
It would be nice to denote compatible range-v3 version or revision explicitly.

**Comment by ericniebler** [comment]
There really isn't one. This repo was forked from an ancient version and then various pieces and parts have been backported over time.

**Comment by xylosper** [comment]
Thank you for your clarification.

In that case, I really think this repo must not be named 'range-v3-vs2015'.
At least, the fact that this repo is not really compatible with range-v3 should be denoted somewhere.
Who could imagine a range-v3-incompatible library whose name is range-v3(-vs2015)?

Futhermore, the README.md file in this repo is misleading.
>This is a fork of Eric Niebler's range-v3 library with extensive (and somewhat invasive) workarounds to support the Visual C++ compiler as released in Microsoft Visual Studio 2015
And, all of remaining parts are just copy-and-paste of README from upstream.
It even contains link to upstream documentation!

**Comment by CaseyCarter** [comment]
Everything from upstream up to and including the commit referenced by the `fork_point` tag (a3e37d6b8e2c6359db0fbb66bf06ba7f8ea11d56) is on `master`. Yes, it's the last commit from November of **2015**. Needless to say, I seriously underestimated the amount of effort that would be required to bring this repo current on VS2015. 

> In that case, I really think this repo must not be named 'range-v3-vs2015'.

I still think the name is appropriate: it truly is the closest thing to range-v3 that can be compiled by VS2015, and ironically enough the code itself is *from* 2015. It could definitely stand to have an updated `README` and a rendering of the documentation from 2015.

**Comment by CaseyCarter** [comment]
> It could definitely stand to have an updated README and a rendering of the documentation from 2015.

And done. Is that clearer?

**Comment by xylosper** [comment]
@CaseyCarter 

First of all, if you feel my words offensive, I apologize.
I appreciate for your efforts for this repo and original range-v3, really. 

Of course, if one just needed a range library which works with visual studio, he or she would be fine with this repo. It doesn't matter that this repo is a fork of range-v3 for such people because what they needed is a range library not range-v3.

However, there are people who want range-v3 not any range library, and for such people, compatibility is very important issue. For instance, there's already an issue in this repo about compatibility: #14.

Anyway, I have no right to make you do something. I just suggested what I thought.
