### ISSUE TITLE
Use with other toolchains?

### ISSUE THREAD

**Issue by rcdailey** [Microsoft/Range-V3-VS2015#4]
Is this fork tied to MSVC exclusively? Or will it continue to work on GCC/Clang/etc?

**Comment by CaseyCarter** [comment]
Our goal is to minimize the differences with upstream as much as possible; there should eventually be *no* differences with ericniebler/range-v3 except workarounds needed for the library to work with VS2015 that the range-v3 maintainers consider too invasive to allow into upstream range-v3. So yes - if something in this library doesn't work with a version of GCC/Clang that upstream range-v3 supports it is a bug.
